### ISSUE TITLE
Not able to build debain/ubuntu package 

### ISSUE THREAD

**Issue by nandeeshb09** [valet-sh/awx-build-deb#1]
Hi Team,

I have ran the debian package builder using ansible playbook and it ran till build-awx-package step ,but further its not going only because of the below error.

Error says install python-setuptools but i have already installed ,even though its not running.
[build-awx-package --- In this step its says successful ,but do not see this directory  /tmp/awx-build/awx-logos/awx/ui/client/assets/logo-login.svg under  /tmp folder.

can you please help me on this?

TASK [build-awx-package : Copy official AWX logos] *********************************************************************************************************************************************************
ok: [awx-debian-build] => (item={u'rusr': True, u'uid': 0, u'rgrp': True, u'xoth': False, u'islnk': False, u'woth': False, u'nlink': 1, u'issock': False, u'mtime': 1555059672.630828, u'gr_name': u'root', u'path': u'/tmp/awx-build/awx-logos/awx/ui/client/assets/logo-login.svg', u'xusr': False, u'atime': 1555059673.1268194, u'inode': 9834212, u'isgid': False, u'size': 38676, u'isdir': False, u'ctime': 1555059672.630828, u'roth': True, u'isblk': False, u'xgrp': False, u'isuid': False, u'dev': 2050, u'wgrp': False, u'isreg': True, u'isfifo': False, u'mode': u'0644', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True})
ok: [awx-debian-build] => (item={u'rusr': True, u'uid': 0, u'rgrp': True, u'xoth': False, u'islnk': False, u'woth': False, u'nlink': 1, u'issock': False, u'mtime': 1555059672.630828, u'gr_name': u'root', u'path': u'/tmp/awx-build/awx-logos/awx/ui/client/assets/logo-header.svg', u'xusr': False, u'atime': 1555059673.1268194, u'inode': 9834211, u'isgid': False, u'size': 38676, u'isdir': False, u'ctime': 1555059672.630828, u'roth': True, u'isblk': False, u'xgrp': False, u'isuid': False, u'dev': 2050, u'wgrp': False, u'isreg': True, u'isfifo': False, u'mode': u'0644', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True})
ok: [awx-debian-build] => (item={u'rusr': True, u'uid': 0, u'rgrp': True, u'xoth': False, u'islnk': False, u'woth': False, u'nlink': 1, u'issock': False, u'mtime': 1555059672.630828, u'gr_name': u'root', u'path': u'/tmp/awx-build/awx-logos/awx/ui/client/assets/awx-logo.pdf', u'xusr': False, u'atime': 1555059673.1268194, u'inode': 9834208, u'isgid': False, u'size': 485970, u'isdir': False, u'ctime': 1555059672.630828, u'roth': True, u'isblk': False, u'xgrp': False, u'isuid': False, u'dev': 2050, u'wgrp': False, u'isreg': True, u'isfifo': False, u'mode': u'0644', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True})
ok: [awx-debian-build] => (item={u'rusr': True, u'uid': 0, u'rgrp': True, u'xoth': False, u'islnk': False, u'woth': False, u'nlink': 1, u'issock': False, u'mtime': 1555059672.630828, u'gr_name': u'root', u'path': u'/tmp/awx-build/awx-logos/awx/ui/client/assets/variables.less', u'xusr': False, u'atime': 1555059673.1268194, u'inode': 9834213, u'isgid': False, u'size': 771, u'isdir': False, u'ctime': 1555059672.630828, u'roth': True, u'isblk': False, u'xgrp': False, u'isuid': False, u'dev': 2050, u'wgrp': False, u'isreg': True, u'isfifo': False, u'mode': u'0644', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True})
ok: [awx-debian-build] => (item={u'rusr': True, u'uid': 0, u'rgrp': True, u'xoth': False, u'islnk': False, u'woth': False, u'nlink': 1, u'issock': False, u'mtime': 1555059672.630828, u'gr_name': u'root', u'path': u'/tmp/awx-build/awx-logos/awx/ui/client/assets/default.strings.json', u'xusr': False, u'atime': 1555059673.1268194, u'inode': 9834209, u'isgid': False, u'size': 53, u'isdir': False, u'ctime': 1555059672.630828, u'roth': True, u'isblk': False, u'xgrp': False, u'isuid': False, u'dev': 2050, u'wgrp': False, u'isreg': True, u'isfifo': False, u'mode': u'0644', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True})
ok: [awx-debian-build] => (item={u'rusr': True, u'uid': 0, u'rgrp': True, u'xoth': False, u'islnk': False, u'woth': False, u'nlink': 1, u'issock': False, u'mtime': 1555059672.630828, u'gr_name': u'root', u'path': u'/tmp/awx-build/awx-logos/awx/ui/client/assets/favicon.ico', u'xusr': False, u'atime': 1555059673.1268194, u'inode': 9834210, u'isgid': False, u'size': 15086, u'isdir': False, u'ctime': 1555059672.630828, u'roth': True, u'isblk': False, u'xgrp': False, u'isuid': False, u'dev': 2050, u'wgrp': False, u'isreg': True, u'isfifo': False, u'mode': u'0644', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True})

TASK [build-awx-package : install python dependencies stage1] **********************************************************************************************************************************************
fatal: [awx-debian-build]: FAILED! => {"changed": false, "msg": "No setuptools found in remote host, please install it first."}

**Comment by dittertp** [comment]
Hi nandeeshb09,

i have tested the "build-debian-package.yml" playbook and it worked without any issue. Do you have modified the playbook? The build process requires lxd and runs inside a container, but for me it seems like you are calling the "awx-debian-build" role directly on your host (what we don't support).

please have a look at our prebuilt Debian packages -> https://github.com/valet-sh/awx-build-deb#use-pre-built-packages


Best Regards,
Philipp

**Comment by nandeeshb09** [comment]
I have made changes in hots file only ,as i have mentioned localhost in hots file.but how to run this playbook build-debian-package.yml inside a lxd container instead of host?

Can you give me a steps to build debian package from yaml file?

That would be more helpful.
please have a look at our prebuilt Debian packages --This is just normal installation rite.

**Comment by dittertp** [comment]
Hi,

sorry for the delay. The playbook "build-debian-package.yml" automatically starts an lxd container and runs the build in that one. You don't have to modify anything. Even modifying the hosts file is not necessary.
