### ISSUE TITLE
awx-manage runworker --only-channels 'websocket.*' fails

### ISSUE THREAD

**Issue by kapouer** [valet-sh/awx-build-deb#2]
In https://github.com/valet-sh/awx-build-deb/blob/1bd34a57879af648a852da73a6246c1f5e5ee37d/roles/build-awx-package/templates/systemd/awx-channels-worker.service.j2#L9

```
usage: awx-manage runworker [-h] [--layer LAYER] [--version] [-v {0,1,2,3}]
                            [--settings SETTINGS] [--pythonpath PYTHONPATH]
                            [--traceback] [--no-color] [--force-color]
                            channels [channels ...]
awx-manage runworker: error: unrecognized arguments: --only-channels
```

**Comment by kapouer** [comment]
Using buster packages 10.0.0-1585939085

**Comment by dittertp** [comment]
Hi,
the "websocket.*" channels worker was removed in version 10 but i forgot to delete the service file. i will rebuild the package with an updated service configuration

**Comment by kapouer** [comment]
So i suppose it just needs to be disabled. Thanks.

**Comment by dittertp** [comment]
that should be enough.

**Comment by dittertp** [comment]
the "experimental" repo has now an updated package.

**Comment by mchubby** [comment]
Hello,

are there specific instructions to use the experimental repo?
`https://dl.cloudsmith.io/public/valet-sh/debian-testing/deb/debian/dists/buster/main/binary-amd64/Packages` (testing == experimental?) still lists `10.0.0-1585939085` as the latest version, so does apt policy


EDIT: oh, swapping the repo directory debian-testing to debian-experimental works!

Registering the key with
`wget https://dl.cloudsmith.io/public/valet-sh/debian-experimental/cfg/gpg/gpg.D15A8AA9D12FDAF0.key -O /etc/apt/trusted.gpg.d/valet-sh-experimental.asc`
