### ISSUE TITLE
missing jmespath for json_query filter

### ISSUE THREAD

**Issue by kapouer** [valet-sh/awx-build-deb#5]
You need to install \"jmespath\" prior to running json_query filter
(using debian-experimental 10.0.0-1591200598)

**Comment by dittertp** [comment]
Hi, i have uploaded a new version to experimental repo. Can you check if the problem is fixed now?

**Comment by kapouer** [comment]
dpkg -L awx | grep jmespath
> /var/lib/awx/venv/awx/lib/python3.7/site-packages/jmespath
...

Cool !
Such a nice piece of software.
Is there a way to simplify the build process (it'd be great awx was part of debian).

**Comment by dittertp** [comment]
I don't think its possible to comply with debian guidelines. The current package contains hundrets of python libraries installed by pip (which is not allowed for packages in the official repo). Some of them are not available as a standalonge package on debian or not in the needed version. Even if it would be possibe, maintaining the package dependencies would be a huge time consuming task.

**Comment by kapouer** [comment]
Closing, and reopening that discussion.
